### ISSUE TITLE
No document to get up and running

### ISSUE THREAD

**Issue by anubhavsrivastava** [travelnxtElements/t-shared-lib#1]
Need document to get up and running in readme.md

**Comment by sounakpal** [comment]
@anubhavsrivastava  Sorry for the inconvenience. This component is ideally used as dependency for other components. You can check the documentation mentioned in https://github.com/travelnxtElements/t-car-category-item

Which is same for most of the components in this organisation.

**Comment by anubhavsrivastava** [comment]
We can have some read me in all projects. It is hard to find documentation for getting up and started.

**Comment by sounakpal** [comment]
Thank you for your feedback. We will try to pick up documentation for all components as soon as possible.

**Comment by cvenkatasuresh** [comment]
@anubhavsrivastava please have a look at air-api-changes branch, we are going to use this branch very soon or may be already in use in application, @ManojC can you please confirm?

**Comment by manojc** [comment]
@anubhavsrivastava ,

We already have started using `polymer cli` to generate proper documentation in every component.
Some of the existing components haven't yet updated with proper documentation.
We will be updating the `read me` files & `demos` for those components soon!

We will get back to you once we are done with it.

**Comment by anubhavsrivastava** [comment]
That would be really helpful!

**Comment by anshulguleria** [comment]
@ManojC Can you recommend one component which has been created with `cli` for reference?

**Comment by manojc** [comment]
@anshulguleria 

check [this](https://github.com/travelnxtElements/t-car-category-item) out

**Comment by ajtejankar** [comment]
Though not all components are in a state where they can be easily consumed, you can navigate and have a glimpse at them by using following urls.
- [Atom Elements](http://atom-project.io/elements/)
- [Travelnxt Elements](http://travelnxtelements.github.io/elements/)
